#security:
#  oauth2:
#    client:
#      id:
#      client-secret: mantraERP12252***
#      access-token-validity-seconds: 3600
#      refresh-token-validity-seconds: 86400
#      privateKey: -----BEGIN RSA PRIVATE KEY-----
#        MIIEpAIBAAKCAQEAvul5CPaFimvlp7ebf3k7lN+pfHwz9puqhPTake+luZ7bnjKt
#        qwyyKZllkNoiAMaxVjXM2tXhivQ95KfTZmOITOEiZ2OuicR4PW70z+4gMnsBL4++
#        1CMi4xMLt1oPzA4ITddpJ/xYP96pJYTZr57+wgd0XlKwID6b4FEexu9FyO7EraeP
#        44wDvpBCf2i4XDBs2bszceHnOKT/cnU3cIkXvo03QtPpROEFJlWZHffnZ+V+tBRC
#        0/j2v7TkUiGogXBUZOnsVuBwP4uiPa69nlUDNeZllaZlo4Sox/ZCZ1K6Sgh4y62v
#        UcXIhEPjy89nZ6S3u5RVKJvfZ3xXLIPmRAXoXwIDAQABAoIBAQCT5SaAjQmyzBdj
#        MFfkDrTbhdE0wLs4pisZSN4yA+bsv2X/Td9ADVvP4ifOaU3CMCqdUJxcQyiwjrmL
#        839PaHfkptwSICTMUUmcveIlWqHSuXuXrtH0YSvboZuH9NscBxrjwqaR9WkgQYvj
#        puFErfVJtqCtmX0b3aS/x9gB4Ma8+vRM0JwvTLq7S1u+ijYC+fnvCQs8iEz9fir/
#        iQVTHOa+EHARcNpe3E7wRR1jG2Uk3UcWncD8naKv+/+8xcLD8J5fV5dxPADsiTfZ
#        bl05G3sfaax5ub5L4t75NoEK/7jLqCBZrVS79h746UeIH0G7gDXup+CsaI+C2MoF
#        9d+9BLVhAoGBAOyhSV00Wl8SGiWx3zPMILzwP+zHPDZRU/6TpwgvUr2cRJcV0Izb
#        6ENmoyRKXT41Sl6TQF9X/Xs0egwLDd2wzZFAcfmdhjCgBmIo55D5hkF7pGS+Mr8A
#        PSjzMQp851DbJ6tWGvAIO1CWykfktAp8fEs4iC1NlIYs5pyteuVJu58JAoGBAM6K
#        I8MgvjQeRtxIEQNU2qWrxLOLCLcOaLCblKrPzwuRu9pN/EW7I20a5InnCI12pTC1
#        P/+g+t718VGXt5HtwN+kWk4l0PRmDqRrrUDgWBlb6+u/WSXy6YkwdoviJXH88lmT
#        t85wJAsos4DEkqpn00BbUyfDbJ6Vk9vDCWs3KL4nAoGBANjnt0IyfSxsgX9QHtNy
#        KAhJCa/XqX/46M+RNSkxh9y647zCiFq2MZ+m86COcg5V9wfeXsGG/Jn1LnLfpyQx
#        rx2YP2GaXakw5ukPqcSglcpstfKKziV66JUi5y8/8yGQ4joSQbsJMKXcsytXnxmF
#        psGk3l74oE6l1faEpwSKo+tRAoGAOZJP/ag23JhD8Es2UtNoTx3eKp3qw/wEOpZj
#        jml2sSbiUivC0j0j1tnUMoxv2d7klPsw57SbuWKc7b14sfiv9qb9dSMdZ8K6+iH5
#        nUfrxsXUsVYZJ3bamh8kLEHRZkC33ThL2ANySJoDzzT8HPvr6tiKCV9z+5B+Mpff
#        HD+336kCgYBU3Hn7JCGIXJWqf0PaO6TXhqwliMx84OI/1mcwyksBXxH9phhnEzPp
#        H2RGiqI81itYjOo6i5d54NWUkTp21TPrM/YGGa/aiUV4JAehbOylwS7Njj90gz5Q
#        2QNszbyfzLBNn3hchIK3UopT45GHX2c2Vvq3/sXkwBXNMflUMQkeQQ==
#        -----END RSA PRIVATE KEY-----
#      publicKey: -----BEGIN PUBLIC KEY-----
#        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvul5CPaFimvlp7ebf3k7
#        lN+pfHwz9puqhPTake+luZ7bnjKtqwyyKZllkNoiAMaxVjXM2tXhivQ95KfTZmOI
#        TOEiZ2OuicR4PW70z+4gMnsBL4++1CMi4xMLt1oPzA4ITddpJ/xYP96pJYTZr57+
#        wgd0XlKwID6b4FEexu9FyO7EraeP44wDvpBCf2i4XDBs2bszceHnOKT/cnU3cIkX
#        vo03QtPpROEFJlWZHffnZ+V+tBRC0/j2v7TkUiGogXBUZOnsVuBwP4uiPa69nlUD
#        NeZllaZlo4Sox/ZCZ1K6Sgh4y62vUcXIhEPjy89nZ6S3u5RVKJvfZ3xXLIPmRAXo
#        XwIDAQAB
#        -----END PUBLIC KEY-----
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization: true
