spring:
  application:
    name: config-server #name of the application
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared #tells spring where to locate the config files
  profiles:
    active: native #we are using native because the config server uses a git repo by default
  security:
    user:
      password: 1234 #the password which apps will use to access its configurations


server:
  port: 8888 #the port where the config-server will be acessible

#
#eureka:
#  instance:
#    prefer-ip-address: true #when the application registers with eureka, it uses its IP address rather than its hostname


opentracing:
  jaeger:
    udp-sender:
      host: 192.168.1.5
      port: 6831
    http-sender:
      url: http://192.168.1.5:6831/api/traces

